# Generated by Django 3.2.15 on 2022-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='settings.MEDIA_ROOT/pdfs/sameer saxena.pdf', upload_to='pdfs/'),
        ),
    ]
